Add model
Traceback (most recent call last):
  File "src/myprogram.py", line 85, in <module>
    train_data = LanguageModel.load_training_data()
TypeError: load_training_data() missing 1 required positional argument: 'path'